//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderdetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Product_Name { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
