//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shopping_Cart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.orderdetails = new HashSet<orderdetail>();
        }
    
        public int Id { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public long CellNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> TotalAmount { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> DeliveryCharge { get; set; }
        public string ShippingAddress { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Payment_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orderdetail> orderdetails { get; set; }
        public virtual user user { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
